services:
  # Продакшн Nginx сервис
  nginx-haccpro:
    restart: unless-stopped
    image: nginx:latest
    container_name: haccpro-nginx
    hostname: haccpro.ru
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=haccpro.ru
      - NGINX_INDEX=index.html
      - NGINX_ROOT=/usr/share/nginx/html
      - NGINX_PORT=80
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-haccpro.rule=Host(`haccpro.ru`)
      - traefik.http.routers.nginx-haccpro.entrypoints=websecure
      - traefik.http.routers.nginx-haccpro.tls=true
      - traefik.http.routers.nginx-haccpro.tls.certresolver=letsencrypt
      - traefik.http.services.nginx-haccpro.loadbalancer.server.port=80
    networks:
      - web
    depends_on:
      - php-fpm
    profiles: [ "prod" ]

  # Локальный Nginx для разработки
  nginx-dev:
    image: nginx:latest
    container_name: haccpro-nginx-dev
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_INDEX=index.html
      - NGINX_ROOT=/usr/share/nginx/html
    depends_on:
      - php-fpm
    networks:
      - app-network  # Используем общую сеть
    profiles: [ "dev" ]

  php-fpm:
    image: php:8.1-fpm
    container_name: haccpro-php
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - web
      - app-network  # Добавляем общую сеть
    profiles: [ "prod", "dev" ]

networks:
  web:
    external: true
  app-network: # Определяем новую сеть
    driver: bridge
  default:
    driver: bridge
