name: Laravel Deployment

concurrency: production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "APP_ENV=production" > .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=https://haccpro.ru" >> .env
          echo "" >> .env
          echo "LOG_CHANNEL=stack" >> .env
          echo "LOG_LEVEL=error" >> .env
          echo "" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=haccp_laravel" >> .env
          echo "DB_USERNAME=haccp_user" >> .env
          echo "DB_PASSWORD=haccp_password" >> .env
          echo "" >> .env
          echo "BROADCAST_DRIVER=log" >> .env
          echo "CACHE_DRIVER=redis" >> .env
          echo "FILESYSTEM_DISK=local" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
          echo "SESSION_DRIVER=file" >> .env
          echo "SESSION_LIFETIME=120" >> .env
          echo "" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PASSWORD=null" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "" >> .env
          echo "MAIL_MAILER=log" >> .env
          echo "MAIL_HOST=mailpit" >> .env
          echo "MAIL_PORT=1025" >> .env
          echo "MAIL_USERNAME=null" >> .env
          echo "MAIL_PASSWORD=null" >> .env
          echo "MAIL_ENCRYPTION=null" >> .env
          echo "MAIL_FROM_ADDRESS=\"hello@example.com\"" >> .env
          echo "MAIL_FROM_NAME=\"HACCPro\"" >> .env
          echo "" >> .env
          echo "TELEGRAM_ALERT_BOT_TOKEN=${{ secrets.TELEGRAM_ALERT_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_ALERT_CHAT_ID=${{ secrets.TELEGRAM_ALERT_CHAT_ID }}" >> .env

      - name: Create project directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: mkdir -p /var/www/haccpro.ru

      - name: Copy files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "/var/www/haccpro.ru"
          strip_components: 0

  build:
    runs-on: ubuntu-latest
    needs: [deploy]
    environment: production
    steps:
      - name: Build and start containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/haccpro.ru/
            # Исправляем права доступа для PHP-FPM
            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache
            # Пересобираем и перезапускаем только изменённые сервисы
            docker compose --profile prod up -d --build
            sleep 15
            # Генерируем APP_KEY если его нет
            docker compose --profile prod exec -T php-fpm php artisan key:generate --force || true
            # Обновляем .env файл на сервере с новым ключом
            APP_KEY=$(docker compose --profile prod exec -T php-fpm php artisan tinker --execute="echo config('app.key');" 2>/dev/null | grep -v "^$" | tail -1) || true
            if [ ! -z "$APP_KEY" ] && [ ! -z "$(echo $APP_KEY | grep 'base64:')" ]; then
              sed -i "s|^APP_KEY=.*|APP_KEY=$APP_KEY|" /var/www/haccpro.ru/.env || true
            fi
            # Перезапускаем PHP-FPM для применения нового ключа
            docker compose --profile prod restart php-fpm
            sleep 5
            docker compose --profile prod exec -T php-fpm php artisan migrate --force || true
            docker compose --profile prod exec -T php-fpm php artisan config:cache || true
            docker compose --profile prod exec -T php-fpm php artisan route:cache || true
            docker compose --profile prod exec -T php-fpm php artisan view:cache || true
            docker compose --profile prod ps

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check website
        uses: wei/curl@v1
        with:
          args: https://haccpro.ru/

  alert:
    name: Alert
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 Деплой завершен!
            
            Автор: ${{ github.actor }}
            Коммит: ${{ github.event.commits[0].message }}
            
            Репозиторий: ${{ github.repository }}
            
            Ссылка на коммит: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            Сайт: https://haccpro.ru
