name: Laravel Deployment

concurrency: production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "APP_ENV=production" > .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=https://haccpro.ru" >> .env
          echo "" >> .env
          echo "LOG_CHANNEL=stack" >> .env
          echo "LOG_LEVEL=error" >> .env
          echo "" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=haccp_laravel" >> .env
          echo "DB_USERNAME=haccp_user" >> .env
          echo "DB_PASSWORD=haccp_password" >> .env
          echo "" >> .env
          echo "BROADCAST_DRIVER=log" >> .env
          echo "CACHE_DRIVER=redis" >> .env
          echo "FILESYSTEM_DISK=local" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
          echo "SESSION_DRIVER=file" >> .env
          echo "SESSION_LIFETIME=120" >> .env
          echo "" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PASSWORD=null" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "" >> .env
          echo "MAIL_MAILER=log" >> .env
          echo "MAIL_HOST=mailpit" >> .env
          echo "MAIL_PORT=1025" >> .env
          echo "MAIL_USERNAME=null" >> .env
          echo "MAIL_PASSWORD=null" >> .env
          echo "MAIL_ENCRYPTION=null" >> .env
          echo "MAIL_FROM_ADDRESS=\"hello@example.com\"" >> .env
          echo "MAIL_FROM_NAME=\"HACCPro\"" >> .env
          echo "" >> .env
          echo "TELEGRAM_ALERT_BOT_TOKEN=${{ secrets.TELEGRAM_ALERT_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_ALERT_CHAT_ID=${{ secrets.TELEGRAM_ALERT_CHAT_ID }}" >> .env

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "/var/www/haccpro.ru"
          strip_components: 0

      - name: Deploy and build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/haccpro.ru/
            
            # Исправляем права доступа
            chown -R www-data:www-data storage bootstrap/cache .env
            chmod -R 775 storage bootstrap/cache
            
            # Быстрый деплой: только перезапуск без пересборки
            docker compose --profile prod up -d --no-build
            
            # Ждем только 3 секунды вместо 15
            sleep 3
            
            # Генерируем APP_KEY только если его нет
            if ! grep -q "APP_KEY=base64:" .env; then
              docker compose --profile prod exec -T php-fpm php artisan key:generate --force
            fi
            
            # Очищаем кэш и применяем миграции
            docker compose --profile prod exec -T php-fpm php artisan config:clear
            docker compose --profile prod exec -T php-fpm php artisan migrate --force
            
            # Проверяем статус
            docker compose --profile prod ps

  test:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Check website
        uses: wei/curl@v1
        with:
          args: https://haccpro.ru/

  alert:
    name: Alert
    needs: [deploy]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 Деплой завершен!
            
            Автор: ${{ github.actor }}
            Коммит: ${{ github.event.commits[0].message }}
            
            Репозиторий: ${{ github.repository }}
            
            Ссылка на коммит: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            Сайт: https://haccpro.ru
